sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: ZA6cJEcmzpkJC138sFHaANKsdgjkBHx+A64RcRsw2Ne/tQ9XmPkS2uAbueW7jr9Pzfj2XOA4LxFch7kvbcQtxcDEeh4FX9sIwDHO8tBPQCT3+KJ1nv0x/GtYsWGUvaHJQijs9UW6p0m8JOsdq8n/82wwy4DwZ01j/IgE45NWGqjPxsGZq6jSW68X+7ZH6FFsbNmz2KVp76zQDN3uLmG2Xl12Dh3CsUP5dzzdsoY2/fDcIa+XbG9KrHd+8uRCXtDcd5kvl19/rBHdyY2tBU8S6Le3j8zUWGB1oGQwibTVQR0Ryn3NCwNTfhTemESjH0tl6CJ6gNnParimNUqXoy4kSkoNzXK0GWSdiP8Owe26Rg7G32nBsO2LN4mrxUmNg+gdgSoDA4xb3dhXlpMuxg6A4JYI90JjgHoch0F/S5SDdHu3hrjyaxInpaBoxeD78MvcQeZ2JjtPtzLZaACb6gZz0RRsjHxi2HJe0lNizI74VpFoyEQ77IfYz3kCgqeSLYx8sWwSkvnyBJpMff0ZIIZmaZnGKjcPwomI+tNYvWQLkB8FQ7uhQ1PI3yYbKXdjlWx14Kt7Zks/wHtyCJyADXFY0hh/zy1Jww83EdMQtAjvfUINZ6Zy8m+zaKgrhcxc5udPUhk5lWrNNjdt+OCjq/e6hDpatwSmJgj7Cc2pY8FYvuI=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-Burgomaster-s-Wife-Volume-03_5580
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy